In [8]:
import numpy as np

def logsumexp(X, axis=None, keepdims=True):
    """Compute LogSumExp along specified axes with numerical stability."""
    X_max = np.max(X, axis=axis, keepdims=True)  # Max for numerical stability
    print( X_max)
    x_minus_x_max = X - X_max
    print( x_minus_x_max)
    exp_x = np.exp( x_minus_x_max)
    print( exp_x)
    sum_x = np.sum( exp_x, axis=axis, keepdims=True)
    print( sum_x)
    res = np.log( sum_x) + X_max
    return res
    
    return np.log(np.sum(np.exp(X - X_max), axis=axis, keepdims=True)) + X_max

def gradient_logsumexp(X, axis=None, keepdims=True):
    """Compute gradient of LogSumExp along specified axes."""
    X_max = np.max(X, axis=axis, keepdims=True)
    exp_X = np.exp(X - X_max)
    softmax = exp_X / np.sum(exp_X, axis=axis, keepdims=True)  # Softmax over axis
    return softmax  # Gradient of LogSumExp

def gradient_max(X, axis=None, keepdims=True):
    """Compute gradient of max(X) along specified axes."""
    X_max = np.max(X, axis=axis, keepdims=True)
    mask = (X == X_max).astype(float)  # Indicator function
    mask /= np.sum(mask, axis=axis, keepdims=True)  # Normalize when multiple maxima exist
    return mask  # Gradient of max(X)

def gradient_f(X, axis_lse=None, axis_max=None, keepdims=True):
    """Compute gradient of f(X) = logsumexp(X) + max(X)."""
    grad_lse = gradient_logsumexp(X, axis=axis_lse, keepdims=keepdims)
    grad_max = gradient_max(X, axis=axis_max, keepdims=keepdims)
    return grad_lse + grad_max  # Sum of both gradients

# Example Usage
X = np.array([
    [[1.0, 2.0, 3.0], [2.0, 3.0, 4.0]],
    [[0.5, 1.5, 2.5], [1.5, 2.5, 3.5]]
])  # Shape: (2, 2, 3)

axis_lse = (1, 2)  # Compute LogSumExp over last two axes
axis_max = (2,)    # Compute max over last axis

grad_output = gradient_f(X, axis_lse=axis_lse, axis_max=axis_max)
print("Gradient of f(X) = LogSumExp(X) + max(X):\n", grad_output)


Gradient of f(X) = LogSumExp(X) + max(X):
 [[[0.02421295 0.06581762 1.17891085]
  [0.06581762 0.17891085 1.48633011]]

 [[0.02421295 0.06581762 1.17891085]
  [0.06581762 0.17891085 1.48633011]]]


In [9]:
X = np.array([
     [0, 1, 2], 
     [3, 4, 5],
     [6, 7, 8]
  ]) 
logsumexp( X, axis=1)


[[2]
 [5]
 [8]]
[[-2 -1  0]
 [-2 -1  0]
 [-2 -1  0]]
[[0.13533528 0.36787944 1.        ]
 [0.13533528 0.36787944 1.        ]
 [0.13533528 0.36787944 1.        ]]
[[1.50321472]
 [1.50321472]
 [1.50321472]]


array([[2.40760596],
       [5.40760596],
       [8.40760596]])

In [10]:
def log_softmax(X):
    """Compute LogSoftmax row-wise for a 2D matrix X."""
    X_max = np.max(X, axis=1, keepdims=True)  # For numerical stability
    exp_X = np.exp(X - X_max)
    softmax_X = exp_X / np.sum(exp_X, axis=1, keepdims=True)
    return np.log(softmax_X)

def log_softmax_gradient(X):
    """Compute the gradient of LogSoftmax for a 2D matrix X."""
    softmax_X = np.exp(X - np.max(X, axis=1, keepdims=True))  # Compute softmax
    softmax_X /= np.sum(softmax_X, axis=1, keepdims=True)

    batch_size, num_classes = X.shape
    I = np.eye(num_classes)  # Identity matrix of size (num_classes x num_classes)


In [11]:
log_softmax( X)

array([[-2.40760596, -1.40760596, -0.40760596],
       [-2.40760596, -1.40760596, -0.40760596],
       [-2.40760596, -1.40760596, -0.40760596]])